"""Update models

Revision ID: 82cf1b4d8900
Revises: 44f2f15ce278
Create Date: 2024-10-14 04:11:07.004163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82cf1b4d8900'
down_revision = '44f2f15ce278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###
